version: 0.2

phases:
  install:
    commands:
      - echo Entering Install Phase
      - sudo yum install -y yum-utils
      - sudo yum-config-manager \
        --add-repo \
        https://download.docker.com/linux/centos/docker-ce.repo
      - sudo yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - sudo systemctl start docker
  build:
    commands:
      - echo Entering Build Phase
      - docker build -t ss-pilot-app:v1 .