version: 0.2

phases:
  install: 
    commands:
      - echo Entering Install Phase
  build:
    commands:
      - echo Entering Build Phase
      - docker --version
      - pwd
      - ls -a
      - echo $(aws ecr get-login-password)
      #- echo $(aws ecr get-login-password) | docker login --username prashant-datamato --password-stdin 350031543021.dkr.ecr.us-east-2.amazonaws.com
      - docker login -u AWS -p $(aws ecr get-login-password) https://350031543021.dkr.ecr.us-east-2.amazonaws.com
      - docker build -t ssapi-ecr-stage .
      - docker tag ssapi-ecr-stage:latest 350031543021.dkr.ecr.us-east-2.amazonaws.com/ssapi-ecr-stage:latest
      - docker push 350031543021.dkr.ecr.us-east-2.amazonaws.com/ssapi-ecr-stage:latest

#artifacts:
#  files:
#    - '**/*'
