version: 0.2

phases:
  install: 
    commands:
      - echo Entering Install Phase
  build:
    commands:
      - echo Entering Build Phase
      - docker --version
      - pwd
      - ls -a
      - docker build -t ss-pilot-app .

artifacts:
  files:
    - '**/*'
