version: 0.2

phases:
  build:
    commands:
      - echo Entering Build Phase
      - docker --version
      - systemctl status docker
      - docker build -t ss-pilot-app .

artifacts:
  files:
    - '**/*'